"""Deciding which files are worth looking at.

Most of a repository is not review material: vendored dependencies, generated stubs,
virtualenvs, minified bundles. Filtering is aggressive and the counts are reported, so
"we reviewed 8 of 340 files" always comes with what the other 332 were.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

log = logging.getLogger(__name__)

EXCLUDED_DIRS = frozenset(
    {
        ".git", ".hg", ".svn", ".tox", ".nox", ".venv", "venv", "env",
        "node_modules", "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
        "site-packages", "dist-packages", "vendor", "third_party",
        "dist", "build", ".eggs", ".idea", ".vscode", ".codesage", "htmlcov",
    }
)
EXCLUDED_SUFFIXES = (".min.js", "_pb2.py", "_pb2_grpc.py", ".pyi")
GENERATED_MARKERS = ("@generated", "do not edit", "autogenerated", "code generated by")


@dataclass(frozen=True)
class SourceFile:
    path: str  # repo-relative, forward slashes
    abs_path: Path
    n_lines: int
    is_test: bool

    def read(self) -> str:
        return self.abs_path.read_text(encoding="utf-8", errors="replace")


@dataclass
class Inventory:
    files: list[SourceFile] = field(default_factory=list)
    skipped: dict[str, int] = field(default_factory=dict)

    def by_path(self, path: str) -> SourceFile | None:
        return next((f for f in self.files if f.path == path), None)

    @property
    def source_files(self) -> list[SourceFile]:
        return [f for f in self.files if not f.is_test]

    @property
    def total_lines(self) -> int:
        return sum(f.n_lines for f in self.files)

    def _skip(self, reason: str) -> None:
        self.skipped[reason] = self.skipped.get(reason, 0) + 1


def is_test_path(rel_path: str) -> bool:
    """Test files are kept, not excluded -- the testing lens needs to know what has
    coverage, and that is only answerable if the tests were indexed."""
    parts = rel_path.split("/")
    name = parts[-1]
    return (
        any(p in ("test", "tests", "testing", "spec") for p in parts[:-1])
        or name.startswith("test_")
        or name.endswith("_test.py")
        or name == "conftest.py"
    )


def discover(
    root: Path, *, max_file_bytes: int = 120_000, include: list[str] | None = None
) -> Inventory:
    """Walk `root` for reviewable Python files.

    `include` restricts the walk to specific repo-relative paths, which is how PR mode
    limits a review to the files a diff touched.
    """
    inventory = Inventory()
    allowed = set(include) if include is not None else None

    for path in sorted(root.rglob("*.py")):
        rel = path.relative_to(root).as_posix()
        if any(part in EXCLUDED_DIRS for part in path.relative_to(root).parts[:-1]):
            continue
        if allowed is not None and rel not in allowed:
            continue
        if rel.endswith(EXCLUDED_SUFFIXES):
            inventory._skip("generated")
            continue

        try:
            size = path.stat().st_size
            if size == 0:
                inventory._skip("empty")
                continue
            if size > max_file_bytes:
                inventory._skip("too large")
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            inventory._skip("unreadable")
            continue

        head = "\n".join(text.split("\n", 8)[:8]).lower()
        if any(marker in head for marker in GENERATED_MARKERS):
            inventory._skip("generated")
            continue

        inventory.files.append(
            SourceFile(
                path=rel,
                abs_path=path,
                n_lines=text.count("\n") + 1,
                is_test=is_test_path(rel),
            )
        )

    log.info("inventory: %d files, skipped %s", len(inventory.files), inventory.skipped or "none")
    return inventory
